Fixed safe shut down feature

diff --git a/contrib/flesctl/fles_input b/contrib/flesctl/fles_input
--- a/contrib/flesctl/fles_input
+++ b/contrib/flesctl/fles_input
@@ -49,15 +49,17 @@ end_readout () {
     for i in ${!SERVER_PID[*]}; do
         kill -s SIGINT ${SERVER_PID[$i]} 2>/dev/null
     done
-    sleep 1
+    sleep 3
     # check if any process is left
     for i in ${!EN_PID[*]}; do
         if kill -0 ${EN_PID[$i]} > /dev/null 2>&1 ;then
+            echo "Cleanup required, en_readout left."
             cleanup
         fi
     done
     for i in ${!SERVER_PID[*]}; do
         if kill -0 ${SERVER_PID[$i]} > /dev/null 2>&1 ; then
+            echo "Cleanup required, flib_server left."
             cleanup
         fi
     done
@@ -103,7 +105,7 @@ for flib in ${!ADDR[*]}; do
 done
 
 # get group ID for cleanup
-SID=$(ps o sid -p ${SERVER_PID[0]} | tail -n1)
+SID=$(trap '' SIGINT SIGTERM SIGHUP && ps o sid -p ${SERVER_PID[0]} | tail -n1)
 
 # block till server is ready
 echo "Waiting for ${#SERVER_PID[@]} flib_server instance(s) ..."
